### ISSUE TITLE
TextViewWithHint fails with v-model

### ISSUE THREAD

**Issue by BigWillie** [tjvantoll/nativescript-IQKeyboardManager#60]
TextViewWithHint doesn't appear to work with v-model in Vue.

Typing into a TextViewWithHint does not update the v-model that is bound to the TextViewWithHint.

`<TextViewWithHint hint="Additional Information" v-model="additional_information"  />`

Thanks,
Rob

**Comment by BigWillie** [comment]
So, I've been able to access the value through a `ref`

`this.$refs.additional_information.nativeView.text`

But its a bit clunky in that the field is erased when it loses focus

**Comment by EddyVerbruggen** [comment]
Just checking: does the `v-model` work when using a plain old `TextView`?

**Comment by BigWillie** [comment]
Yep - works with plain old TextView

**Comment by EddyVerbruggen** [comment]
Thanks for confirming that. I forgot to wire something up. Fixed in 1.5.1 (available now!).

**Comment by BigWillie** [comment]
Hi @EddyVerbruggen - sorry to bug you again... Upgraded to 1.5.1, and problem persists. Thanks
